In [60]:
import pandas as pd

In [61]:
tags = pd.read_csv('tags_34.csv')

In [62]:
data = pd.read_csv('street.csv')

In [63]:
tags.head()

,Unnamed: 0,title_url,tags
0,0,black-friday-cyber-monday-deals-save-money-cou...,"['34st-Style', 'medium-words', 'medium-headlin..."
1,1,knives-out-movie-rian-johnson-chris-evans-dani...,"['34st-FilmTV', 'featured', 'film']"
2,2,dizengoff-frozen-labneh-solomonov-zahav-philad...,"['34st-Style', 'medium-words', 'top', 'style']"
3,3,frances-quinlan-hop-along-likewise-rare-thing-...,"['34st-Music', 'featured']"
4,4,penn-epsilon-eta-president-profile-environment...,"['ego', 'climate-issue']"

In [64]:
data.head()

,Unnamed: 0,id,uuid,title,slug,content,published_date,title_url
0,0,37011,9a808ff0-d495-4c59-a4e3-4ce266c47ad4,Frances Quinlan Comes Full Circle in Her Solo ...,frances-quinlan-hop-along-likewise-rare-thing-...,In an age when algorithms often dictate our ta...,2020-01-20 02:06:02,2020/01/frances-quinlan-hop-along-likewise-rar...
1,1,37013,853a59a8-3c9d-4b6c-89e1-a29af5fcaec1,The Oscars Once Again Prove Outdated and Irrel...,oscars-academy-award-joker-the-irishman-1917-t...,"Whether willfully or not, the Oscars are consi...",2020-01-20 01:32:49,2020/01/oscars-academy-award-joker-the-irishma...
2,2,37015,77db94a6-1a11-4c89-a3ae-4d76a0e68843,'Good Luck Everybody' is AJJ at Their Most Cau...,ajj-good-luck-everybody-album-review-sean-bonn...,It’s impossible to have a neutral opinion of A...,2020-01-19 22:42:36,2020/01/ajj-good-luck-everybody-album-review-s...
3,3,35451,19298e33-96c5-4b05-a13b-39da2ed5d4a9,Can Cakes and Sweaters Enact Political Change?,subversive-embroidery-subversive-baking-subver...,"For better or for worse, art, media, and prote...",2020-01-15 23:49:57,2020/01/subversiveembroidery-subversivebaking-...
4,4,37006,5e13f58f-9d6d-436c-83de-536fb20f32c2,Street's Favorite Movies of the Decade,best-movies-decade-2010s-moonlight-carol-mad-m...,This decade in cinema has been a wild ride. We...,2019-12-11 20:52:39,2019/12/best-movies-decade-2010s-moonlight-car...

In [65]:
tags.shape

(13546, 3)

In [66]:
data.shape

(13513, 8)

In [67]:
tags = tags.rename(columns={"title_url": "slug"})

In [68]:
join = pd.merge(data, tags, how='left', on = 'slug')

In [69]:
join.shape

(13564, 10)

In [70]:
join.head()

,Unnamed: 0_x,id,uuid,title,slug,content,published_date,title_url,Unnamed: 0_y,tags
0,0,37011,9a808ff0-d495-4c59-a4e3-4ce266c47ad4,Frances Quinlan Comes Full Circle in Her Solo ...,frances-quinlan-hop-along-likewise-rare-thing-...,In an age when algorithms often dictate our ta...,2020-01-20 02:06:02,2020/01/frances-quinlan-hop-along-likewise-rar...,3.0,"['34st-Music', 'featured']"
1,1,37013,853a59a8-3c9d-4b6c-89e1-a29af5fcaec1,The Oscars Once Again Prove Outdated and Irrel...,oscars-academy-award-joker-the-irishman-1917-t...,"Whether willfully or not, the Oscars are consi...",2020-01-20 01:32:49,2020/01/oscars-academy-award-joker-the-irishma...,28.0,"['34st-FilmTV', 'top', 'film']"
2,2,37015,77db94a6-1a11-4c89-a3ae-4d76a0e68843,'Good Luck Everybody' is AJJ at Their Most Cau...,ajj-good-luck-everybody-album-review-sean-bonn...,It’s impossible to have a neutral opinion of A...,2020-01-19 22:42:36,2020/01/ajj-good-luck-everybody-album-review-s...,18.0,"['top', 'music']"
3,3,35451,19298e33-96c5-4b05-a13b-39da2ed5d4a9,Can Cakes and Sweaters Enact Political Change?,subversive-embroidery-subversive-baking-subver...,"For better or for worse, art, media, and prote...",2020-01-15 23:49:57,2020/01/subversiveembroidery-subversivebaking-...,NaN,NaN
4,4,37006,5e13f58f-9d6d-436c-83de-536fb20f32c2,Street's Favorite Movies of the Decade,best-movies-decade-2010s-moonlight-carol-mad-m...,This decade in cinema has been a wild ride. We...,2019-12-11 20:52:39,2019/12/best-movies-decade-2010s-moonlight-car...,42.0,"['34st-FilmTV', 'top', 'film']"

In [71]:
join = join.drop(['Unnamed: 0_x', 'Unnamed: 0_y'], axis=1)

In [72]:
join['tags'] = join['tags'].str.replace("'", "")

In [73]:
join['tags'] = join['tags'].str.lower()

In [74]:
join['tags'] = join['tags'].str.strip('[]').str.split(',')

In [88]:
join.head()

,id,uuid,title,slug,content,published_date,title_url,tags
0,37011,9a808ff0-d495-4c59-a4e3-4ce266c47ad4,Frances Quinlan Comes Full Circle in Her Solo ...,frances-quinlan-hop-along-likewise-rare-thing-...,In an age when algorithms often dictate our ta...,2020-01-20 02:06:02,2020/01/frances-quinlan-hop-along-likewise-rar...,"[34st-music, featured]"
1,37013,853a59a8-3c9d-4b6c-89e1-a29af5fcaec1,The Oscars Once Again Prove Outdated and Irrel...,oscars-academy-award-joker-the-irishman-1917-t...,"Whether willfully or not, the Oscars are consi...",2020-01-20 01:32:49,2020/01/oscars-academy-award-joker-the-irishma...,"[34st-filmtv, top, film]"
2,37015,77db94a6-1a11-4c89-a3ae-4d76a0e68843,'Good Luck Everybody' is AJJ at Their Most Cau...,ajj-good-luck-everybody-album-review-sean-bonn...,It’s impossible to have a neutral opinion of A...,2020-01-19 22:42:36,2020/01/ajj-good-luck-everybody-album-review-s...,"[top, music]"
3,35451,19298e33-96c5-4b05-a13b-39da2ed5d4a9,Can Cakes and Sweaters Enact Political Change?,subversive-embroidery-subversive-baking-subver...,"For better or for worse, art, media, and prote...",2020-01-15 23:49:57,2020/01/subversiveembroidery-subversivebaking-...,[]
4,37006,5e13f58f-9d6d-436c-83de-536fb20f32c2,Street's Favorite Movies of the Decade,best-movies-decade-2010s-moonlight-carol-mad-m...,This decade in cinema has been a wild ride. We...,2019-12-11 20:52:39,2019/12/best-movies-decade-2010s-moonlight-car...,"[34st-filmtv, top, film]"

In [76]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()

In [77]:
#replace Na with empty list
for row in join.loc[join.tags.isnull(), 'tags'].index:
    join.at[row, 'tags'] = []

In [78]:
s = join['tags']

In [79]:
encoded = pd.DataFrame(mlb.fit_transform(s),columns=mlb.classes_, index=join.index)

In [80]:
encoded.head()
encoded.shape

(13564, 9752)

In [81]:
encoded.sum(axis=0)

                                        34
  "01-19-17"                             9
  "02-                                   1
  "02-16-17"                            11
  "02-16-19"                             1
  "04-13-17"                            11
  "11-3-16"                              2
  "latest-edition"                       2
  and children                           1
  dr. jess                               1
  elyce helford                          1
  emily lindin                           1
  femininity                             1
  flow-chart                             1
  gendered behavior                      1
  han                                    1
  hike                                   1
  long-form                              2
  october 27th                           1
  racism                                 1
  rosie                                  1
  self slut shaming                      1
  slut shaming                           1
  sti                                    1
  upenn. university of pennsylvania      1
  women                                  5
 !!!                                    46
 "40th and walnut mcdonalds"             1
 "71"                                    2
 "90s"                                   2
                                      ...
review                                  87
reviews                                  1
root                                     1
rosh hashanah                            1
round-up                                 1
rush                                     1
sam brodey                               1
sex                                      2
sexy                                     1
short-words                              2
shoutouts                               10
snl                                      1
south-philly                             1
spotlight                               25
street style                             1
style                                   22
tech                                    23
television                               1
the kooks                                1
the round up                             2
tips                                     1
top                                    441
tweet of the week                      565
uncategorized                           79
university-city                          4
vice                                     1
vice-and-virtue                        446
wawa                                     1
wharton                                  1
word-on-the-street                     166
Length: 9752, dtype: int64

In [82]:
columns = list(encoded)
d = []
for i in columns:
    s = encoded[i].sum()
    if (s <= 1):
        d.append(i)

In [83]:
len(d)

6608

In [84]:
#drop columns
encoded = encoded.drop(d, axis=1)

In [89]:
encoded.head()

,,"""01-19-17""","""02-16-17""","""04-13-17""","""11-3-16""","""latest-edition""",long-form,women,!!!,"""71""",...,spotlight,style,tech,the round up,top,tweet of the week,uncategorized,university-city,vice-and-virtue,word-on-the-street
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [85]:
encoded.sum(axis=0)

                             34
  "01-19-17"                  9
  "02-16-17"                 11
  "04-13-17"                 11
  "11-3-16"                   2
  "latest-edition"            2
  long-form                   2
  women                       5
 !!!                         46
 "71"                         2
 "90s"                        2
 "ben and jerrys"             3
 "bob and barbaras"           4
 "bobbys burger palace"       3
 "brr its cold"               2
 "brussels sprouts"           3
 "buis"                       6
 "cavanaughs"                 2
 "chickies and petes"         2
 "destinys child"             2
 "don memos"                  3
 "dos and donts"              5
 "drinkers west"              2
 "dunkin donuts"              2
 "egos top ten lists"         2
 "gennaros"                   2
 "governors ball"             3
 "hershels"                   2
 "honest toms"                6
 "jacks mannequin"            2
                           ...
letter                       99
letter-from-the-editor       56
long-words                    4
lowbrow                     795
multimedia                   30
music                      1566
news                          4
northern liberties            2
other                       631
overheard at penn            27
overheards                   29
penn                          9
philly                        3
photo                         5
reading terminal market       3
recap                         2
review                       87
sex                           2
short-words                   2
shoutouts                    10
spotlight                    25
style                        22
tech                         23
the round up                  2
top                         441
tweet of the week           565
uncategorized                79
university-city               4
vice-and-virtue             446
word-on-the-street          166
Length: 3144, dtype: int64

In [96]:
#merge back 
encoded.shape

(13564, 3144)